project_id = "gjovmocrotguhjrqroin"

[functions.gerar-contrato-pdf]
verify_jwt = false

[functions.extrair-variaveis-docx]
verify_jwt = false

[functions.zapsign]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.processar-alertas-sla]
verify_jwt = false
