project_id = "gjovmocrotguhjrqroin"

[functions.gerar-contrato-pdf]
verify_jwt = false

[functions.extrair-variaveis-docx]
verify_jwt = false

[functions.zapsign]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.processar-alertas-sla]
verify_jwt = false

[functions.processar-automacoes]
verify_jwt = false

[functions.asaas]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.gerar-faturas-mensais]
verify_jwt = false

[functions.regua-cobranca]
verify_jwt = false

[functions.sincronizar-faturas-asaas]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false
